device cuda:0
pygame 2.0.2 (SDL 2.0.16, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
2022-02-18 19:53:13,532, INFO: model_score: tensor([], dtype=torch.float64)
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/ryd/miniconda3/envs/rl/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ryd/miniconda3/envs/rl/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryd/JIDI_Competition/vec_env/schmem_vec_env.py", line 140, in _subproc_worker
    last_obs_sequence_dict = _write_obs(env.reset(), None)
  File "/home/ryd/JIDI_Competition/vec_env/schmem_vec_env.py", line 115, in _write_obs
    ob_oppo = ob_oppo.reshape(1, *ob_oppo.shape)
AttributeError: 'list' object has no attribute 'reshape'
Traceback (most recent call last):
  File "/home/ryd/JIDI_Competition/rl_trainer/main.py", line 81, in <module>
    main(args)
  File "/home/ryd/JIDI_Competition/rl_trainer/main.py", line 70, in main
    runner.rollout(args.train_epoch)
  File "/home/ryd/JIDI_Competition/rl_trainer/runner.py", line 127, in rollout
    o = self.env.reset()
  File "/home/ryd/JIDI_Competition/vec_env/schmem_vec_env.py", line 61, in reset
    return self._decode_obses([pipe.recv() for pipe in self.parent_pipes])
  File "/home/ryd/JIDI_Competition/vec_env/schmem_vec_env.py", line 61, in <listcomp>
    return self._decode_obses([pipe.recv() for pipe in self.parent_pipes])
  File "/home/ryd/miniconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/ryd/miniconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/ryd/miniconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError